#
# Travis CI build script.
# https://travis-ci.org/stevengj/nlopt
#

language: cpp
sudo: false

env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=TRUE
    - CTEST_PARALLEL_LEVEL=2

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          # cmake 3.x
          - george-edison55-precise-backports
          packages:
          - swig
          - python-dev
          - python-numpy
          - guile-2.0-dev
          - octave3.2-headers
          - cmake
          - cmake-data
          - g++-mingw-w64-i686
          - gcc-mingw-w64-i686
          - binutils-mingw-w64-i686
          - g++-mingw-w64-x86-64
          - gcc-mingw-w64-x86-64
          - binutils-mingw-w64-x86-64
      script:
        # native
        - mkdir build && pushd build
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DWITH_CXX=ON ..
        - make -j2 && make install
        - make tests && ctest && cpack
        - popd
        # 32-bit mingw-w64 cross-compile
        - mkdir build_mingw32 && pushd build_mingw32
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DWITH_CXX=ON
            -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-i686-w64-mingw32.cmake
            -DWITH_SWIG=OFF -DBUILD_PYTHON=OFF -DBUILD_GUILE=OFF
            -DBUILD_OCTAVE=OFF -DBUILD_MATLAB=OFF ..
        - make -j2 && make install
        - make tests && cpack
        - popd
        # 64-bit mingw-w64 cross-compile
        - mkdir build_mingw64 && pushd build_mingw64
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DWITH_CXX=ON
            -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-x86_64-w64-mingw32.cmake
            -DWITH_SWIG=OFF -DBUILD_PYTHON=OFF -DBUILD_GUILE=OFF
            -DBUILD_OCTAVE=OFF -DBUILD_MATLAB=OFF ..
        - make -j2 && make install
        - make tests && cpack
        - popd

    - os: osx
      before_install:
        - brew tap homebrew/python
        - brew tap homebrew/science
        - brew update
      install:
        - brew install swig numpy guile octave
      script:
        - mkdir build && pushd build
        - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DWITH_CXX=ON ..
        - make && make install
        - make tests && ctest && cpack
        - popd
