language: cpp
sudo: false

addons:
  apt:
    sources:
    packages:
    - swig
    - python-dev
    - python-numpy
    - guile-2.0-dev
    - octave3.2-headers
    - cmake
    - g++-mingw-w64-i686
    - gcc-mingw-w64-i686
    - binutils-mingw-w64-i686
    - g++-mingw-w64-x86-64
    - gcc-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64

script:
  - ./autogen.sh --no-configure
  - mkdir build && pushd build
  - ../configure --prefix=$HOME/.local --enable-shared --enable-maintainer-mode --with-cxx --without-guile
  - make -j2
  - make install
  - python ../test/test_std.py
  - rm -rf * ~/.local
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBUILD_SHARED_LIBS=ON -DWITH_CXX=ON ..
  - make install -j2 && make tests -j2 && ctest -j2 --output-on-failure
  - rm -rf * ~/.local
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBUILD_SHARED_LIBS=ON -DWITH_CXX=ON -DBUILD_PYTHON=OFF -DBUILD_OCTAVE=OFF -DBUILD_GUILE=OFF -DCMAKE_TOOLCHAIN_FILE=$PWD/../cmake/toolchain-i686-w64-mingw32.cmake ..
  - make install -j2 && make tests -j2
  - rm -rf * ~/.local
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBUILD_SHARED_LIBS=ON -DWITH_CXX=ON -DBUILD_PYTHON=OFF -DBUILD_OCTAVE=OFF -DBUILD_GUILE=OFF -DCMAKE_TOOLCHAIN_FILE=$PWD/../cmake/toolchain-x86_64-w64-mingw32.cmake ..
  - make install -j2 && make tests -j2
